packages:
- apps/*
- internal/*
- packages/*
- shared/*
- tooling/*

catalog:
  "@t3-oss/env-nextjs": "^0.13.11"
  tsc-alias: ^1.8.16
  hono: ^4.12.14
  typescript: ^6.0.3
  tsx: ^4.21.0
  zod: ^4.3.6
  dotenv-cli: ^11.0.0
  semver: ^7.7.4

catalogs:
  node22:
    '@types/node': ^25.6.0
